language: rust
rust:
  - 1.39.0

before_install:
- docker pull target/consensource:rust-base

script:
- >
  docker run -v `pwd`:/consensource -t target/consensource:rust-base /bin/sh -c
  "
  cd consensource;
  cd common;
  cargo fmt -- --check;
  cargo build;
  cd ../database
  cargo fmt -- --check
  cargo build
  cd ../cli
  cargo fmt -- --check
  cargo test
  cargo build
  cd ../processor
  cargo fmt -- --check
  cargo build
  cd ../state_delta_subscriber
  cargo fmt -- --check
  cargo build
  cd ../rest_api
  rustup default nightly
  cargo +nightly fmt -- --check
  cargo build
  "
